-- AlterTable
ALTER TABLE "Destination" ADD COLUMN     "activities" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "attractions" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "averageTemperature" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bestSeason" TEXT NOT NULL DEFAULT 'All Year',
ADD COLUMN     "continent" TEXT NOT NULL DEFAULT 'Unknown',
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'Unknown',
ADD COLUMN     "language" TEXT NOT NULL DEFAULT 'Unknown',
ADD COLUMN     "latitude" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "longitude" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "rating" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "timeZone" TEXT NOT NULL DEFAULT 'Unknown',
ADD COLUMN     "travelTips" TEXT[] DEFAULT ARRAY[]::TEXT[];
